name: grdwindinversion-tests
channels:
    - conda-forge

dependencies:
    - python=3.10

    # development
    - ipython
    - pre-commit
    - jupyterlab
    - jupyterlab_code_formatter
    - isort
    - black
    - dask-labextension

    # testing
    - pytest
    - pytest-reportlog
    - hypothesis
    - coverage

    # I/O
    - rioxarray
    - h5netcdf
    - zarr

    # data
    - numpy=2.1.*
    - scipy=1.14.*
    - xarray=2024.10.*
    - dask=2024.11.*
    - pandas=2.2.*
    - shapely=2.0.*
    - xsar

    - xarray-datatree

    # processing
    - more-itertools
    - tqdm
    - lxml
    - importlib_resources
    - xmlschema=3.4.3
