S1A:
    GMF_VV_NAME: "gmf_cmod5n"
    GMF_VH_NAME: "gmf_s1_v2"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: True
S1B:
    GMF_VV_NAME: "gmf_cmod5n"
    GMF_VH_NAME: "gmf_s1_v2"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: True
RS2:
    GMF_VV_NAME: "gmf_cmod5n"
    GMF_VH_NAME: "gmf_rs2_v2"
    dsig_VH_NAME: "gmf_rs2_v2"
    apply_flattening: False
    recalibration: True
RCM:
    GMF_VV_NAME: "gmf_cmod5n"
    GMF_VH_NAME: "gmf_rcm_noaa"
    dsig_VH_NAME: "gmf_s1_v2"
    apply_flattening: True
    recalibration: True
